\section{クラス ModuleManager::InvalidArguments}
\label{classsource__py_1_1_module_manager_1_1_module_manager_1_1_invalid_arguments}\index{source\_\-py::ModuleManager::ModuleManager::InvalidArguments@{source\_\-py::ModuleManager::ModuleManager::InvalidArguments}}
指定引数不正時例外処理用内部クラス  


{\bf ModuleManager::Error}を継承しています。



\subsection{説明}
指定引数不正時例外処理用内部クラス 

 ModuleManager.py の 204 行で定義されています。